### ISSUE TITLE
Migrate from ulex to sedlex

### ISSUE THREAD

**Issue by XVilka** [Beluga-lang/Beluga#108]
Long story short - ulex is dying, mainstream depends on the camlp4, which is dead, fork depends on the camlp5, which seems dead too. This prevents from porting Beluga to more modern OCaml versions and dependencies versions.

See these links for more information:
- https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985/4
- https://github.com/ocaml/opam-repository/pull/14351

Sedlex is an active maintained project by OCaml community: https://github.com/ocaml-community/sedlex

**Comment by XVilka** [comment]
And the official Camlp4 deprecation announcement: https://discuss.ocaml.org/t/the-end-of-camlp4/4216

**Comment by pientka** [comment]
Thanks for bringing this up!  @tsani  is reworking our parser using sedlex.

**Comment by XVilka** [comment]
@tsani can you please make a new release for opam? 
https://opam.ocaml.org/packages/beluga/ shows last release was a loooooong time ago. 
You can use [dune-release](https://github.com/samoht/dune-release) for easy publishing, since you switched to dune anyway. It will help you create a pull request to https://github.com/ocaml/opam-repository/
