### ISSUE TITLE
Different behaviour with impossible versus empty LF pattern

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#109]
The following program is in the negative test suite:

```
--coverage
constructorless : type.

nat : type.
zero : nat.
succ : nat -> nat.

schema constructorlesses = constructorless;

rec empty-example-3X : (g:constructorlesses) [g |- constructorless] -> [ |- nat] =
  fn c =>
    case c of 
      [g |- {} ]
;
```
Replacing the case-expression with `impossible c` results in a program that is accepted by the coverage checker, but `c` is not impossible. Specifically, there is the case for a parameter variable.

**Comment by Ailrun** [comment]
Is this related with #107?

**Comment by tsani** [comment]
Possibly. It's hard to say for sure. In #107 it looks like `impossible` is completely broken because there are obviously constructors that work; I can replace the `impossible st` in #107 with a case-expression over `st` that is nonempty. However, in this bug, I can't replace the `impossible` with a nonempty case-expression.

**Comment by tsani** [comment]
A related issue came up in IRC: it appears that `impossible` looks only at an empty LF context, so it ignores parameter variables. Here is the example:
```
LF empty : type =;
schema absurd = empty;

rec bang : {g : absurd} {E : [g |- empty]} [ |- empty] =
/ total E (bang g E) /
mlam g => mlam E =>
    impossible [g ⊢ E] % in {E : [g ⊢ empty]} [g]
;
```
`[g |- E]` is _not_ impossible, however! In particular, you can write a nonempty case-expression examining `[g |- E]`: the only possible branch is a parameter variable.
If you uncomment the explicit context, we get the expected error, that the expression is in fact _not_ impossible.
It appears that during parsing, when the context is omitted, the empty context is supplied. This later on (in reconstruction, specifically `elBranch`) doesn't get correctly compared with the *actual* context used in the expression, so the coverage checker ends up computing the coverage goals for `[|- E]`, which is *actually* impossible.
