### ISSUE TITLE
New release for opam

### ISSUE THREAD

**Issue by XVilka** [Beluga-lang/Beluga#126]
There were [A LOT](https://github.com/Beluga-lang/Beluga/compare/v0.8.2...master) of changes since the [latest opam release](https://opam.ocaml.org/packages/beluga/) (0.8.2). And OCaml 4.09 release is coming, while [camlp4 won't be available](https://discuss.ocaml.org/t/the-end-of-camlp4/4216) for this release, so people won't install Beluga from opam without pinning.

**Comment by XVilka** [comment]
I suppose this is the target milestone, right？ https://github.com/Beluga-lang/Beluga/milestone/1

**Comment by tsani** [comment]
The remaining issues on that milestone are mainly nice-to-haves rather than must-haves, so one could prepare a `1.0` release of Beluga from the `master` branch today.

I'm not closely involved with the Beluga project anymore, but maybe @Ailrun would prepare the release.

**Comment by tsani** [comment]
I've moved those remaining  `v1.0` issues to `v2.0`.

**Comment by pientka** [comment]
On Sep 12, 2019, at 8:07 AM, Jacob Thomas Errington <notifications@github.com<mailto:notifications@github.com>> wrote:


I have it on my agenda to prepare the new opam release soon. The frontend has already been rewritten to no longer rewrite ulex or campl4.

Are you still planning the prepare the new opam release? — I think that Clare isn’t quite familiar with what it entails, but I am sure he is willing to help out, if you explain briefly to him what needs to be done.

Thanks for all your work, Brigitte

**Comment by Ailrun** [comment]
What steps are needed to release Beluga? I can release a new version if I know the necessary steps.

**Comment by tsani** [comment]
I've never done an opam release before, so I don't know. The bulk of the work in this ticket is figuring out what the steps are. You might possibly need to get in touch with Francisco Ferreira who was the last person to do a release, afaik.

**Comment by MartyO256** [comment]
Beluga v1.0 was released on opam earlier this year.
