### ISSUE TITLE
Convertibility check for CTyp against ClTyp causes crash

### ISSUE THREAD

**Issue by marcelgoh** [Beluga-lang/Beluga#127]
When entering a statement to prove, Harpoon seems to stumble with forall-quantified variables. I have looked at `debug.out` (attached: [debug.txt](https://github.com/Beluga-lang/Beluga/files/3607529/debug.txt)) but I'm unsure of the exact issue.

This is the console output:

```
# %: prove unique
Statement to prove (C-d to abort): (g:tctx)[g |- hastype E (T[])] -> [g |- hastype E (T'[])] -> [|- eq T T']
Induction order: 1
Uncaught exception.
Please report this as a bug.
- Unhandled exception: File "src/core/whnf.ml", line 1797, characters 33-38: Pattern matching failed;
```

**Comment by tsani** [comment]
Appears to be an issue relating to `auto-solve-trivial` selecting the context `g : tctx` as a solution.

Can you look into this, @Ailrun ?

**Comment by tsani** [comment]
Nevermind, turns out the fix was quite easy.
