### ISSUE TITLE
Splitting doesn't work properly for proper Pi-types

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#132]
Load this signature.
```
LF tp : type =
  | arr : tp → tp → tp
;

% algorithmic subtyping
LF asub : tp → tp → type =
  % subtyping for arrow, references
  | a-arr : asub B1 A1 → asub A2 B2 →
            asub (arr A1 A2) (arr B1 B2)
;
```

And try to prove `{A : [|- tp]} [|- asub A A]` with Harpoon (induction order 1).
Split on `[|- A]`. We get this proof state:

```
Meta-context:
  {A : [ |- tp]}*
  {Y : [ |- tp]}^i
  {X : [ |- tp]}^i
Computational context:
--------------------------------------------------------------------------------
[ |- asub A A]
```
The goal is incorrect. We expect that `A` in the goal should be refined to `arr X Y` since this is the proof obligation in the case for `arr`.

**Comment by Ailrun** [comment]
Does a commit before comp split make the same problem?

**Comment by tsani** [comment]
@Ailrun excellent idea to check this. Yes, the bug persists even before the introduction of comp split.

**Comment by tsani** [comment]
Actually there used to be another bug involving splitting that I resolved in my local tree.

When we split, we have to check whether we're splitting on a variable with an induction star, in order to correctly propagate the stars to the subterms. However, this check was only implemented for *computation* variables. This was fine because all our examples that did induction splitting would split on a computation variable (e.g. `x7`). But now that in this example we're splitting on a metavariable inside a box, we need a separate induction-star check.

There was a commented-out check (`is_meta_inductive`) that I brought back and adjusted, so now the stars are propagated correctly. But there still remains the issue of the refinement substitution not quite working.

**Comment by tsani** [comment]
The refinement substitution computed by the coverage checker does not include the substitution for the scrutinee in the case that we are matching on a metavariable used in a dependent type. In other words, the reason our box-matching so far has worked is that we weren't matching on a variable appearing in another type; we were matching on boxes coming from the non-dependent function space. There is a function in `reconstruct.ml` that adjusts the refinement substitution to include a replacement for the scrutinee, to be used when doing proper dependent pattern matching.
