### ISSUE TITLE
Introduce an automatic code style formatter

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/Beluga#134]
IMO, Current code style is sufficiently inconsistent to introduce a tool for managing it.

~I found that ocamlformat is not so bad in terms of the number of options, reliability, etc.~

How about introducing it and formatting codes with it?

**Comment by Ailrun** [comment]
I tried `ocamlformat` and `ocp-indent`, and no one work really well...
1. `ocamlformat`
    There are too few options to control code style reasonably. It introduces a lot of conflict between formatted codes and tuareg mode indentation.
2. `ocp-indent`
    It does not remove redundant spaces, inconsistent linefeed, etc. Furthermore, it also creates issues related to indentation.

**Comment by tsani** [comment]
Yes, automatic style checking / fixing seems like a tough issue to tackle, tbh. I'm not sure how to handle it.

**Comment by MartyO256** [comment]
An `ocamlformat` configuration was added in #266. However, most files in the core library and Harpoon are not formatted, and are instead in an `.ocamlformat-ignore` file. Automatic formatting may be enabled later for new modules.
