### ISSUE TITLE
Introduce `suffices` command

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#142]
Look at the backwards closed lemma for weak normalization of STLC:

```
rec bwd_closed' : {A:[|- tp]}{M:[|- tm A]}{M':[|- tm A]}{S:[ |- step M M']} Reduce [|- A] [ |- M'] -> Reduce [|- A] [ |- M] =
/ total a (bwd_closed' a) /
 mlam A, M, M' => mlam MS => fn r => case [|- A] of
| [|- b] => let I ha = r in I (halts_step [ |- MS] ha)
| [|- arr A B] =>
  let Arr ha f = r in
    Arr (halts_step [ |- MS] ha)
	(mlam N => fn rn =>
	 bwd_closed' [|- B] [|- _ ] [|- _ ] [ |- stepapp MS] (f [ |- N] rn))
;
```

In the case for `arr A B`, we have to construct a relatively complex computational term: `mlam N => fn rn => bwd_closed' [|- B] [|- _] [|- _] [|- stepapp MS] (f [|- N] rn)`.

It would be nice if this term could be constructed using Harpoon interactively, instead of by just writing this monster after `solve`.
This is similar to Coq's `refine` tactic, which allows one to work backwards by saying "I want to complete the proof using this function" and then go back to (interactively) fill in its arguments.

This raises several questions.
* If we do `refine Arr`, we expect to generate two subgoals, one for each argument. However, the subgoals now have dependencies *between them*. Previously this never happened. Presumably, this means that the subgoals must be solved in dependency order. I think this is fine, but I think it would involve a relatively substantial change:
  * How do we detect dependencies?
  * Can we forego dependency analysis and instead just require solving the subgoals from left to right?
  * What to do about implicit arguments? Will the user have to specify all the implicit arguments first, since technically they are dependencies of the explicit arguments which come later?
  * Can we instead allow solving the explicit arguments only, causing instantiations for the implicit arguments? How do we display the goal type then, since it will contain uninstantiated variables?!

**Comment by tsani** [comment]
Following a discussion in the Harpoon meeting Tuesday, a tactic like `refine` would definitely be nice to have. We should instead call it `suffices`, since the idea of this proof tactic, at a high level, is to mimic the reasoning mathematicians use when saying "it suffices to show X, Y, ... [by L]". For us, `L` would be some function (either a lemma, a constructor, perhaps even a recursive call) and `X, Y, ...` are the types of its arguments. So this is actually a way of writing the usual `by lemma L a b as x; solve x`. But since it is supposed to solve the goal and since the user is supposed to specify the types of the arguments, this ought to pin down any implicit arguments immediately, and the user can instead focus on constructing the arguments (interactively).
We still may need to force the user to solve the new subgoals from left-to-right unless we implement a dependency analysis. (I don't think implementing such an analysis would be hard, so a simple improvement would be to add it later. A first stab of such an analysis could just be to see if all explicit arguments to be constructed are on the left of a simple function space instead of a dependent function space.)

The syntax of this in a proof script would look something like:
```
suffices by i to show
- tau_1
  { cD_1 | cG; P_1 }
- tau_2
  { cD_2 | cG; P_2 }
- ...
```
All the `cG` ought to be the same, but the `cD` later on may refer back to the previous arguments in the case of pi-types.

The typing rule for this directive ought to be something like
```
cD_i; cG |- P_i <== tau_i   for all i         cD; cG |- i' ==> tau'     ???
-------------------------------------------------------------------------------------------
cD; cG |- suffices by i' to show tau_i { cD_i | cG; P_i} <== tau
```
The missing premise `???` needs to mimic the way applications work in Beluga. This probably ought to be an auxiliary judgment.

I am a bit concerned about this premise. Meta-application in Beluga works something like this:
```
cD; cG |- i ==> Pibox (X : U, tau')  cD; cG |- C <== U
--------------------------------------------------------------------------
cD; cG |- mapp (i, C) ==> tau'[C/X]
```

So what if in the tentative typing rule for the `suffices` directive, we use a _proof_ to construct an index-object passed to `i'` (that is, we're doing a forall-elimination instead of a plain implication-elimination) ? That would mean that we don't actually have the `C`! We have a proof whose translation gives us `[C]`, and we don't even have a notion of substitution for proofs. So we _can't_ mimic dependent function application!

Therefore, I think one needs to forbid using proofs to eliminate dependent function spaces.

Typically in a Beluga program, one writes all the dependent function types at the front, followed by all the simple functions, and typically all the dependencies are passed implicitly. In that case, the situation I'm concerned with is a nonissue since there are no explicit index-objects being constructed by `suffices`.
But look at the backwards-closed lemma again: we see many explicit pi-types used. If we forbid using `suffices` to eliminate pi-types, the user must then write a command such as `suffices by (bwd_closed' C1 C2 C3 ...) to show ...` in order to explicitly eliminate all the pi-types leaving only a simple function type left. I personally find this unergonomic, but perhaps it's acceptable.

The translation for the `suffices` directive would look something like:
```
cD_i; cG |- P_i ~~> e_i <== tau_i   for all i
------------------------------------------------------------------------------------------
cD; cG |- suffices by i' to show tau_i { cD_i | cG; P_i} ~~> i' e_1 e_2 ... <== tau

**Comment by Ailrun** [comment]
7a9f4633a48cab9da7bb595e370698310764e2f6 introduced parts of the command.

**Comment by tsani** [comment]
I implemented it.

**Comment by Ailrun** [comment]
We still need to implement `ih` part of it, right? That's what I meant :)

**Comment by tsani** [comment]
We're just going to drop the `ih`/`lemma` qualifier from `suffices by` so that it matches ordinary `by`.

There was one kind of `suffices by` variant that I was thinking about that could be interesting, as it would allow backwards reasoning on the LF level. But I'm not sure this is a good idea yet, as the metatheory would be quite different from the metatheory for computational `suffices by`. The syntax could just be `LF suffices by R` where R is an LF Pi-type. The idea would be to then introduce subgoals for each premise of this LF Pi as *computational* subgoals, but that's fine because we can use unboxing to lower them to the LF layer in the translation. 
This `LF suffices by` would be really nice for splitting up the construction of complicated LF terms, but I still need to think about it a lot.

**Comment by Ailrun** [comment]
Yes, actually I already dropped one. What I mean is internal implementation, not a user command.

For LF level suffices, I agree that sounds interesting. It might be a bit complex in theory though...
