### ISSUE TITLE
Harpoon user's guide

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#150]
We should produce a document that explains all the Harpoon commands, how to use them, and so on. It would be really great to also integrate a help system into Harpoon, so a user can type `help` at the prompt and get a list of all the commands with a brief synopsis. Typing `help cmd` would display more detailed documentation about the command `cmd`.

It would be *really* great if there were some way to avoid duplicating the command explanations between the documentation and the help system; perhaps the explanations given in the help system can be loaded from files that we embed into the harpoon binary? These same files can be used by a script for generating the documentation.

**Comment by Ailrun** [comment]
I think one more critical duplication will be introduced in parsing and help system. It would be wonderful if there is a way to reduce this duplication too.

**Comment by tsani** [comment]
I'm not sure I follow.
Is it that there is a duplication in the sense that the help system has to list all the available commands, but parsing also essentially has to list all the available commands?

In that case, I agree, and it would be nice to eliminate it.
We can perhaps abstract the commands into a "final" encoding, so instead of having commands defined by constructors, we define a command as a record of all the things a command can do:
- it needs a parser
- it needs a connection to its associated tactic
- etc.

But this introduces a circularity I'm not sure how to resolve. The parser should return this object, but this object describes how it is supposed to be parsed.

Perhaps we can define a bunch of term-level tags `type cmd_tag = [ `intros | `split | `help | ... ]` so there is a centralized representation of commands.
The help system is then essentially a function `cmd_tag -> help` where `help` is some type that represents the help.
The parser needs to return a tag PLUS associated data specific to that tag, so perhaps we should use GADTs here. For example, the help command's associated data is itself actually a `cmd_tag`.
The prover can analyze a tag + associated data as before to invoke the appropriate tactic.
Since the help command by itself is supposed to list commands, we actually need to construct a list of all tags, but this can be done right underneath the definition of `cmd_tag`, so if anyone adds a new command, they also add it to the list.

Anyway, do you think this reduces duplication / helps to prevent adding a tag and forgetting a parser / forgetting to add help / forgetting to integrate with the prover, etc.?

**Comment by Ailrun** [comment]
If it's possible, but IDK too how to achieve it, or even whether it's possible or not.

**Comment by tsani** [comment]
We now have hand-written documentation hosted at https://beluga-lang.readthedocs.org/ automatically integrated with this repository.
