### ISSUE TITLE
Automatic code documentation

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#151]
I try to write as much code documentation as I can. It would be great if we could integrate OCamldoc into the mix so that we can generate HTML documentation for the code. This would greatly help newcomers to the project so they can more easily locate files. For example, a newcomer may want to compose two `msub`s, but they don't know to look for `Whnf.mcomp`. We can write a comment on the `msub` type itself that links to `Whnf.mcomp` to facilitate this. In fact, perhaps all helper functions for working with `msub`s should be linked from the type definition of `msub`.

This would also help me since (I believe) merlin supports displaying documentation directly in Emacs, and there are a handful of functions whose argument orders can be mixed up (multiple arguments of the same type in a row).

**Comment by MartyO256** [comment]
A Github pages website now gets published on every commit to the `master` branch using [`odoc`](https://github.com/ocaml/odoc). You can find the output here: https://beluga-lang.github.io/Beluga/
