### ISSUE TITLE
Resumable Harpoon sessions

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#152]
Currently, a Harpoon session has to be completed in one sitting, which is dangerous. What about power failures, forced computed updates, etc. ?

Harpoon's state is represented completed by a tree of objects, so this tree can be serialized and saved to disk. In fact, the state can be saved after every command. These save states can be kept in memory to allow the user to roll back commands / revert to an earlier state, and they can also be persisted to disk (in `%appdata%/Harpoon` on Windows and `.local/share/harpoon` on Linux (and presumably macOS).

Harpoon should also store a hash of the loaded signature inside the save states to detect whether the signature was changed "behind our backs" and warn the user of this.

I think that allowing rollbacks during a session is somewhat difficult because there is currently no nice way to visualize an entire proof. (Viewing the whole proof script is not _nice_.)

- [ ] Implement copying of Harpoon state. Harpoon's state is mutable, so a proper deep copy operation is necessary. Alternatively, rewriting to use only immutable data structures would resolve this.
- [ ] Implement (de)serialization of Harpoon state. This can be to whatever format is most convenient, s-expressions, JSON, or even a binary format. We should perhaps pull in some kind of library that makes generating these outputs easier.
- [ ] Implement saving serialized Harpoon states. This should be in a platform-independent way. Ideally a library can provide us with a function to calculate a path to some "app-specific data directory" (`$XDG_something` on linux, something on macOS, and `%appdata%` on Windows). Otherwise we can implement such a module ourselves provided we can reliably determine the platform Harpoon is running on.
- [ ] Implement loading serialized Harpoon states. This can be via a command-line option `--resume X` but a better user experience later could be via a prompt "there is an unfinished Harpoon session at `path`: `signature path`; `proven theorems`; `unproven theorems`. Do you want to resume it, ignore it, or delete it?"
- [ ] Implement warning for modifying signatures "Warning: the signature associated with this proof has been modified since the last session. Proceed anyway?"
- [ ] Implement live rollback. I'm imagining a curses interface when the `rollback` command is executed. Pressing left or right navigates between states, and within each state, the user can see the list of subgoals. Pressing up or down in this view selects a subgoal and shows its proof state (available assumptions and goal type).

**Comment by tsani** [comment]
@Ailrun do you feel like taking this issue? It's a big one, so feel free to just tackle one of the bullet-points.

**Comment by Ailrun** [comment]
OK, After I will finish the evaluation, I will take this.

**Comment by Ailrun** [comment]
@tsani Could you explain why you think the first step is required? It looks somewhat redundant to me since we can do it with serialization.

**Comment by tsani** [comment]
Yeah it's basically the same thing. I was thinking you can implement an operation that takes the mutable Harpoon object graph and converts into one immutable data structure which can then be serialized relatively straightforwardly. This seems useful for doing in-memory checkpoints of the prover state, since I don't think we should only have on-disk checkpoints.

**Comment by Ailrun** [comment]
Oh, I see. It might worth to rewrite mutable data flows.

**Comment by Ailrun** [comment]
I am gonna use the proof script language for resumable sessions

**Comment by tsani** [comment]
This is implemented now. Harpoon will reconstruct the previous sessions from the incomplete proofs in the loaded signature. The `save` function allows the user to suspend their current session.
