### ISSUE TITLE
Improve subgoal paths

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#164]
"Don't-care" nondeterministic actions should not extend the subgoal path, as they make it less useful. Morally, `invert` is a don't-care action (it could be performed automatically, if we could figure out how to implement that while avoiding infinite loops). Likewise for `intros`.

- [x] skip subgoal path extension for `intros`
- [x] skip subgoal path extension for `invert` (rather, for `split` in general if a unique case is produced)

From the user's point of view, after performing `intros` or `invert` they are still "in the same subgoal"; it's just that new assumptions are available. The subgoal path should mirror the user's expectation here.

**Comment by Ailrun** [comment]
I think we should determine how we will describe the root goal.
By using just `root`? or using other word? or symbol? which symbol will be appropriate? etc...

**Comment by tsani** [comment]
How about the name of the theorem? This also makes it clearer when switching between theorems which one you're working on.

**Comment by Ailrun** [comment]
That sounds good.
