### ISSUE TITLE
Can't construct copy functions interactively

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#171]
Try to prove `[|- tm] -> [|- tm]` in Harpoon.
The auto-intros tactic will bring `x : [|- tm]` into scope, and auto-solve-trivial will solve the goal using `x`. Since this all happens before we get a prompt, we can't disable the automation.

I'm not sure how one should resolve this. It seems bad to have automation disabled by default. Perhaps we can use environment variables to control the initial state of specific automatic tactics?

**Comment by Ailrun** [comment]
or using an option like `--turn-off-auto` to disable automation by default?

**Comment by Ailrun** [comment]
or if it is able to provide more automation, replace `auto_solve_trivial` with a command like `auto` (I think nathaniel is doing something like this now, right?)

**Comment by tsani** [comment]
Maybe something like `--auto-off [NAMES]` to have specific automation disabled on start. This is annoying to integrate with our current test harness, however.

**Comment by tsani** [comment]
This has been resolved by commit b331f8ee which prevents auto-solve-trivial from finishing a theorem.
