### ISSUE TITLE
Support numeric total orders in external syntax

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#172]
Whereas Beluga uses _symbolic_ total orders represented in external syntax as `/ total x (foo _ _ _ x) /`, Harpoon uses _numeric_ total orders, for which there is no external syntax.
Since we need to be able to splice Harpoon proofs back into files, we need to reflect the internal total order (which is numeric) into external syntax. Generating a symbolic order would be silly. (We would always use `x` and have to generate the right number of underscores.) So why bother?
Instead we should allow writing `/ total 2 /` for the numeric total order "2". That is, induction on the second argument, not counting implicits. This generalizes naturally for lexicographic orders (which are partially supported) by writing `/ total [1, 2] /`.

**Comment by Ailrun** [comment]
It's almost purely matter of parsing, right? I mean, totality checker already supports numeric orders, so it does not need to be changed, am I correct?

**Comment by tsani** [comment]
Yes, we need to adjust the parser to accept numeric orders in totality declarations, and we need to adjust signature reconstruction to check that the numeric order is valid.
