### ISSUE TITLE
Harpoon session settings pragma

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#176]
We would like to allow representing Harpoon session configuration in Beluga files, using a pragma.
For example, `--harpoon auto_intros=off.` would be placed before the mutual block that identifies the session that would have this setting active. Such an approach to configuring theorems and prover settings resolves issue #171, since the user can write
```
--harpoon auto_solve_trivial=off.
proof copy : (g : ctx) [ g |- tm ] -> [ g |- tm ] =
/ total 1 /
?
;
```
to configure the copy theorem & the prover settings that will make it provable.

These session settings should be saved along with the theorems when saving a session back to a file. When a session is complete (all theorems are proven) no settings pragma should appear in the output. (See issue #152.)

**Comment by Ailrun** [comment]
Do you think automation settings should belong to a sesssion? (currently it belongs to the entire state)

**Comment by tsani** [comment]
@Ailrun Personally I think automation settings should have some kind of scoping since I think this gives the greatest control over what's happening. But that's too much work I think, perhaps instead the settings should be session scoped.

I don't think synchronizing the pragma with the session state is easy (or really feasible) in general, since one must detect any existing pragma and replace it.
@Ailrun what are your thoughts on a compromise: we allow the user to write these pragmas, but we will not synchronize the pragma when serializing the session. This way, the user can still implement copy functions (issue #171) but the implementation will not be so hard.
A naive implementation of this compromise would be bad because the user could have issued commands such as `toggle-automation ...` during their session, and this information would be load by the reload that follows the `serialize` command. To resolve this, one can store the current automation state for the session before performing the reload.

**Comment by tsani** [comment]
And by "some kind of scoping" I mean that the user can set the automation settings at any level, and lower-level settings take precedence. That is, they override higher level ones. Like I said, this is very complicated, but I think it's the most powerful.

**Comment by Ailrun** [comment]
Just a quick idea: what if we add automation tactic as a part of proofscript?

**Comment by tsani** [comment]
Actually this is an interesting idea. We could store it as metadata within the incomplete proof. So each `?` could have metadata associated with it to specify the values of the automation. But then that means that automation setting scope is very very narrow, and child subgoals would have to be made to inherit the automation settings of their parent.

One approach that I don't think is good would be to introduce specific nodes (constructors for `command`). These nodes would not really have a type-level behaviour, and would require making changes to type reconstruction for proofs.

**Comment by Ailrun** [comment]
NVM, it would not provide session/state level setting...

**Comment by tsani** [comment]
The idea of a session settings pragma is intriguing but very difficult to implement because of the way that we rewrite signature files. Finding the correct location to place the pragma and overwriting the existing pragma, if any, would be complex and brittle. For now, users will have to accept that session settings will not be preserved through cold Harpoon restarts.
