### ISSUE TITLE
Error in type checking rule for If Statement

### ISSUE THREAD

**Issue by stheph** [Beluga-lang/Beluga#18]
Currently, in check.ml, in the case for If (e, e1, e2), we type check e1 twice rather than checking e1 and e2. Correcting this causes an error to arise in two of the test cases, examples/freshML/cconv.bel and examples/freshML/term-crec.bel. Considering the way the errors arise, there's probably an error in the else branch of some if statement in the two test cases (in the case of cconv.bel, it's the last branch of genTVar, but I haven't looked into term-crec.bel)

**Comment by tsani** [comment]
You're right. In `examples/freshML/cconv.bel` the error is `recursive call not structurally smaller`, but clearly, it is!

```beluga
env:type.
enil : env.
econs:  term -> env -> env.

schema tctx =  term  ;

rec genTVar :(g:tctx){#p:[g |- term]} [g |- env] -> [arg':target, xve:target |-  target] =
/ total env (genTVar g p env) /
mlam #p => fn env => case env  of
| [g |- enil] => [arg':target, xve |-  tfst xve]
| [g |- econs H T]  =>
  if [g |- H] == [g |- #p] then
     [arg':target, xve |-  arg']
  else
     (let [arg':target, xve:target |- U] = genTVar [g |- #p ] [g |- T ]  in
     [x:target, xve:target |- U[x, (tsnd xve)] ])
;
```

The function is decreasing on the `env` argument, which in the case-expression is matched to `econs H T`. The recursive call is on `T`, which is smaller. So why is this rejected?

**Comment by tsani** [comment]
An interesting remark, though: Beluga *does* seem to check both branches of an if-expression!

We can't fool the typechecker with something like

```beluga
LF bogus : type =
    | bbbogus : bogus;

rec foo : Bool -> Bool =
fn x => if x then ttrue else [ |- bbbogus ]
;
```

I would expect, by looking at the relevant section of `check.ml`, that the else-branch be ignored. But Beluga does correctly report that it's expecting a Bool, yet I wrote a box-expression.

**Comment by tsani** [comment]
One more thing.

In #29 @pientka suggests removing the built-in `Bool` type and first-class equality. In that case, this issue is moot (and so are a handful of others, e.g. PRs #26 and #27). The relevant files in `examples` should then be removed, since they use the first-class equality check `==`.
