### ISSUE TITLE
Refactor prover.ml

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#188]
`prover.ml` contains a submodule `Prover`, itself with submodules `Session` and `State`.
At the bottom of `prover.ml` is the main Harpoon REPL.

This should be refactored as follows
- `Session` should become its own module. This is similar to the refactor we did by making `Theorem` its own module.
- `State` should become its own module and perhaps be renamed to `Prover`. Several functions that live at the level of the current `Prover` submodule should probably be moved into `State`.
- The remaining code in `Prover` should be in a `REPL` module.

**Comment by tsani** [comment]
@Ailrun would you be interested in tackling this issue actually? I noticed some comments by you regarding wanted to refactor serialization (putting it in its own module), so maybe it would be good to refactor prover.ml in general.

**Comment by Ailrun** [comment]
Oh, sure. It would be better to refactor the module. I will try it.

**Comment by tsani** [comment]
Hey @Ailrun I'm going to take over this issue and resolve it today, before working on getting undo working.

**Comment by Ailrun** [comment]
Got it.
