### ISSUE TITLE
The external pretty printer poduces erroneous programs

### ISSUE THREAD

**Issue by fferreira** [Beluga-lang/Beluga#19]
The code produced by he pretty printer prettyext.ml is incorrect.
This impacts the +html feature.

**Comment by fferreira** [comment]
After fixing this, the cases studies should be regenerated and the related section should be added back to the web page

**Comment by MartyO256** [comment]
The HTML pretty-printer was re-implemented in #266. The case studies have not been updated on the web page.

**Comment by MartyO256** [comment]
A modernized version of the website for Beluga can be found in this repository: https://github.com/MartyO256/beluga-site

The case studies in that version use the HTML pretty-printer implemented in #266 https://martyo256.github.io/beluga-site/casestudies

The test cases in the `examples` directory are now being used to test the pretty-printer for the external syntax. It is guaranteed that parsing an example, pretty-printing it, then parsing the pretty-printed output results in the same Beluga signature (without considering locations and inline comments). https://github.com/Beluga-lang/Beluga/blob/master/test/test_parser/test_pp.ml
