### ISSUE TITLE
File "src/core/index.ml", line 956, characters 50-55: Pattern matching failed

### ISSUE THREAD

**Issue by Niols** [Beluga-lang/Beluga#2]
The following file is working fine:

    % file fail.bel
    
    datatype foo : type =
      | bar : foo
    ;
    
    rec fail : [|- foo] -> [|- foo] =
    / total f (fail f) /
    fn f => case f of
    | [|- bar] => [|- bar]
    ;

but add a little `v` some where and beluga fails without catching the error.
The following code:

    % file fail.bel
    
    datatype foo : type =
      | bar : foo
    ;
    
    rec fail : [|- foo] -> [|- foo] =
    / total f (fail f) /
    fn f => case f of
    v                                        % note the v here
    | [|- bar] => [|- bar]
    ;

will produce:

    Compilation started at Thu May 21 15:48:49
    
    beluga /home/niols/Complogic/nicolas.jeannerod/articles/TAPL/fail.bel
    Uncaught exception.
    Please report this as a bug.
    
    ## Type Reconstruction: /home/niols/Complogic/nicolas.jeannerod/articles/TAPL/fail.bel ##
    File "src/core/index.ml", line 956, characters 50-55: Pattern matching failed
    Compilation exited abnormally with code 1 at Thu May 21 15:48:49

**Comment by davidthibodeau** [comment]
In its current form, the parser (`cmp_branch`) does not require a branch to have a right-hand side as we use `(case v of [ |- {}])` to mean `impossible v in []`. However, it makes no distinctions between boxed pattern which are handled when lacking a right hand side and more general patterns such as a single variable which should have one.

The cases for `cmp_branch` and `cmp_branch_pattern` should be refactored to take into account the two different behaviours.
