### ISSUE TITLE
Non-recursive total functions allow circular definitions

### ISSUE THREAD

**Issue by tsani** [Beluga-lang/Beluga#217]
Load this signature

```
LF u : type = u : u;

rec foo : [|- u] → [⊢ u] =
/ total /
fn x ⇒ foo x;
```

This needs to trigger an error, because `foo` is defined as total, but non-recursive. Therefore any recursive call in the body should produce an error saying something like "This recursive call is forbidden because the totality declaration for `foo` indicates that it is not recursive."

**Comment by MartyO256** [comment]
Loading the following signature:
```
LF nat : type =
| zero : nat
| succ : nat -> nat
;

LF leq : nat -> nat -> type =
| leq/z : leq zero N
| leq/s : leq N1 N2 -> leq (succ N1) (succ N2)
;

proof leq-trans : [ |- leq N1 N2] -> [ |- leq N2 N3] -> [ |- leq N1 N3] =
/ total /
intros
{ N : ( |- nat), N1 : ( |- nat), N2 : ( |- nat)
| x : [ |- leq N N1], x1 : [ |- leq N1 N2]
;
?
}
;

```
It is possible to complete the proof by inputting `by leq-trans x x1 as k` then `solve k`.
Instead, we should expect a type-checking error since the recursive call is not structurally smaller, or prevent recursively calling `leq-trans`.
Specifying `/ total 1 /` instead of `/ total /` prevents this circular definition.

**Comment by Ailrun** [comment]
Then how can we use `/ trust /`? Is that not allowed?

**Comment by tsani** [comment]
@Ailrun internally we track the status of the declaration with 4 different states.

```
  type 'order total_dec_kind =
    [ `inductive of 'order
    | `not_recursive
    | `trust (* trusted *)
    | `partial (* not total *)
    ]
```

So we just need to check the declaration type and forbid recursive declarations only in the `not_recursive` case (that is `/ total /`)

**Comment by Ailrun** [comment]
@tsani Oh, I mistook this issue. What I though about is 'if we consider an empty induction order in harpoon prompt as a / total /, then how can a user use / trust /?'

**Comment by tsani** [comment]
Oh I see what you're saying. 

Right now, we just don't support `/ trust /` in Harpoon. One solution might be to change the way we interpret the induction order prompt. The user would be required to specify a full declaration like `total 5`, `total` or `trust`. Basically the same thing as what they would write in the Beluga source code, but without the forward slashes. This would also mean that we can support the named induction order style i.e. `total x (foo _ _ _ x)`.

**Comment by Ailrun** [comment]
Yeah, I fixed some of them but there's `/ trust /` in the original mechanization, so I couldn't help it.

**Comment by Ailrun** [comment]
3baf56e068e04e1a03ae1ccf16c8cf04207a7262 made the `trust` order work in the harpoon order prompt.
