### ISSUE TITLE
Stating/Proving a substitution lemma

### ISSUE THREAD

**Issue by ionathanch** [Beluga-lang/Beluga#222]
First off, sorry if this is the wrong place to ask, I couldn't figure out if there was a place to ask beginner/user questions. Is there a mailing list or forum of some sort?

Now, I'm (roughly) trying to prove the following lemma for my language (`A`, `B` here are expressions `exp` and T presumably a `{x:exp} exp`):

```
if (equiv A B) then (equiv T[x := A] T[x := B])
```

where `equiv` is an equivalence relation for terms (doesn't matter what it is exactly, the important thing is that I know I can prove it on paper). I'm trying just to state the lemma in Beluga, but I can't figure how to even write it down. This was my first attempt:

```beluga
rec lem_subst : [ ⊢ equiv A B] → [ ⊢ equiv T[A] T[B]] = ?;
```

I get the error `Cannot construct a type for free variable T (leftover constraints)`. I've tried a few things including adding `{T : [ exp ⊢ exp]}`, declaring `schema ctx = exp;` then adding `{g:ctx} {T : [ g ⊢ exp]}` with `g`s in every context, and other similar tweaks like that, but none of it has worked. I looked at a few examples in the repo trying to find some substitution examples and I found a few things that looked like `[g1 ⊢# g2]` and `[g2 ⊢ M[$R]]`, but I couldn't find what those things mean in the [reference guide](http://complogic.cs.mcgill.ca/beluga/userguide2/userguide.pdf). (I also couldn't quite understand sections 3.5 and 3.6 of that guide, which talk about metavariables, parameter variables, and substitution variables.)

How am I supposed to state this lemma? Am I approaching this the wrong way?

**Comment by Ailrun** [comment]
What you found is a substitution variable, and I believe it is probably not what you want to use for your lemma.

I think the following type works: `rec lem_subst : {T : [x : exp |- exp]} [|- equiv A B] -> [|- equiv T[A] T[B]]`. Have you tried this?

**Comment by ionathanch** [comment]
It looks like that works, thanks! What's the difference between `[exp |- exp]` and `[x: exp |- exp]`? I would've thought the former was a nondependent synonym for the latter.

**Comment by Ailrun** [comment]
With something like `[exp |- exp]`, it is not possible to know which part of the latter `exp` should be substituted by a term in a substitution, whereas `[x : exp |- exp]` means if you ever used `x` to create the latter `exp`, it will be replaced by such a term when you applied a substitution.

**Comment by ionathanch** [comment]
A quick follow-up to this: how should I case-match on `[x:exp |- exp]`? I've tried `mlam T ⇒ fun e ⇒ case [x:exp ⊢ T] of ...`, but it tells me that the `type synthesis of term failed` at `T`.

**Comment by tsani** [comment]
> With something like `[exp |- exp]`, it is not possible to know which part of the latter `exp` should be substituted by a term in a substitution, whereas `[x : exp |- exp]` means if you ever used `x` to create the latter `exp`, it will be replaced by such a term when you applied a substitution.

The syntax `[x |- exp]` invents an unknown for the type of x and tries to infer it by unification, whereas `[x : exp |- exp]` is a fully determined contextual type.

> A quick follow-up to this: how should I case-match on `[x:exp |- exp]`? I've tried `mlam T ⇒ fun e ⇒ case [x:exp ⊢ T] of ...`, but it tells me that the `type synthesis of term failed` at `T`.
> 
> EDIT: Never mind, I used `fun` instead of `fn` by mistake. It's not in the reference, is that a new keyword?

`fun` is similar to `function` in OCaml if you're familiar with it. It was added when copattern support was (partially) added. I'm not sure what the status of `fun` is nowadays, but I suspect that it interacts poorly with totality checking, so you're probably best to stick to the basic `fn` and `case`.
