### ISSUE TITLE
Wrong block projections on inversion

### ISSUE THREAD

**Issue by MartyO256** [Beluga-lang/Beluga#228]
Load the following signature:

```
LF kind : type =
| t : kind
| pi : kind -> (con -> kind) -> kind
and con : type =
| rec' : kind -> (con -> con -> con) -> con -> con
; --name kind K. --name con C a.

LF kd-wf : kind -> type =; --name kd-wf Dwf wf.
LF kd-equiv : kind -> kind -> type =; --name kd-equiv Dequiv equiv.
LF kd-sub : kind -> kind -> type =; --name kd-sub Dsub sub.

LF cn-of : con -> kind -> type =
| cn-of/rec :
  kd-wf K ->
  ({ a : con } cn-of a (pi K (\l. t)) ->
      { b : con } cn-of b K ->
      cn-of (C1 a b) t) ->
  cn-of C2 K ->
    cn-of (rec' K C1 C2) t
; --name cn-of Dof cof.

LF cn-equiv : con -> con -> kind -> type =
| cn-equiv/rec :
  kd-equiv K K' ->
  ({ a : con } cn-of a (pi K (\l. t)) ->
   { b : con } cn-of b K ->
   cn-equiv (C1 a b) (C1' a b) t) ->
  cn-equiv C2 C2' K ->
    cn-equiv (rec' K C1 C2) (rec' K' C1' C2') t
; --name cn-equiv Dequiv equiv.

schema conbind-reg =
  some [K : kind, wf : kd-wf K]
  block (a : con, da : cn-of a K);

LF cn-equiv-reg/e :  con -> con -> kind -> type =
| cn-equiv-reg/i : cn-of C1 K -> cn-of C2 K -> kd-wf K -> cn-equiv-reg/e C1 C2 K
;

proof cn-equiv-reg :
  (g : conbind-reg)
  [g |- cn-equiv C1 C2 K] ->
    [g |- cn-equiv-reg/e C1 C2 K] =
/ total 1 /
intros
{ g : conbind-reg, C : (g |- con), C1 : (g |- con), K : (g |- kind)
| x : [g |- cn-equiv C C1 K]
; split x as
  case cn-equiv/rec:
  { g : conbind-reg,
    K1 : (g |- kind),
    C2 : (g, a3 : con, a2 : con |- con),
    C4 : (g |- con),
    K2 : (g |- kind),
    C3 : (g, a5 : con, a4 : con |- con),
    C5 : (g |- con),
    Dequiv : (g |- kd-equiv K1 K2),
    Dequiv1 :
      (g, a : con, z8 : cn-of a (pi (K1[..]) (\l. t)), b : con,
       y9 : cn-of b (K1[..]) |- cn-equiv (C2[.., a, b]) (C3[.., a, b]) t),
    Dequiv2 : (g |- cn-equiv C4 C5 K1)
  | x :
      [g |-
         cn-equiv (rec' K1 (\y2. \x2. C2) C4) (rec' K2 (\y2. \x2. C3) C5) t]
  ; by cn-equiv-reg
         [_, b1 : block (a : con, da : cn-of a (pi (K1[..]) (\l. t))),
          b2 : block (b : con, db : cn-of b (K1[..])) |-
            Dequiv1[.., b1.1, b1.2, b2.1, b2.2]]
      as q;
    ?
  }
}
;
```

`cn-equiv-reg/e` is defined like that to simultaneously get `cn-of C1 K`, `cn-of C2 K` and `kd-wf K` when inverting `cn-equiv-reg/e C1 C2 K`.

Above, `q` has the correct type
```
[g, b1 : block (a : con, da : cn-of a (pi (K1[..]) (\l. t))),
     b2 : block (b : con, db : cn-of b (K1[..])) |-
       cn-equiv-reg/e (C6[.., b1.1, b2.1]) (C7[.., b1.1, b2.1]) t]
```
where `C6` and `C7` have `a : con` and `b : con` substituted in.

Using the following command

```
invert q
```

we get these new variables in the meta-context

```
  Dof :
    (g, a : con, y2 : cn-of a (pi (K1[..]) (\l. t)), b : con,
     x2 : cn-of b (K1[..]) |- cn-of (C6[.., y2, b]) t)
  Dof1 :
    (g, a : con, z2 : cn-of a (pi (K1[..]) (\l. t)), b : con,
     y3 : cn-of b (K1[..]) |- cn-of (C7[.., z2, b]) t)
  Dwf : (g, a : con, b : con |- kd-wf t)
```

as opposed to

```
  Dof :
    (g, a : con, y2 : cn-of a (pi (K1[..]) (\l. t)), b : con,
     x2 : cn-of b (K1[..]) |- cn-of (C6[.., a, b]) t)
  Dof1 :
    (g, a : con, z2 : cn-of a (pi (K1[..]) (\l. t)), b : con,
     y3 : cn-of b (K1[..]) |- cn-of (C7[.., a, b]) t)
  Dwf : (g, a : con, b : con |- kd-wf t)
```

Having the variables in the former meta-context correctly raises an error upon type reconstruction since `y2` and `z2` do not have type `con`.

Reading in the `debug.out` of that scenario, `unifyMMVarTermProj` seems to work, yielding `[unifyMMVarTermProj] t_flat = .., a, b`.
However, `genObj` returns those erroneous types.

**Comment by tsani** [comment]
My hunch is that there's a bug when flattening contexts involving more than one block that leads to an off-by-one error. This is actually the first time I see a context with multiple blocks in it.

**Comment by tsani** [comment]
I believe that the source of the problem is the function `etaExpandStrGeneric` in `convSigma.ml`. It is called by `genSpine` in `coverage.ml` that constructs a spine of mmvars. `genSpine` does this by traversing the type of an LF constructor and eta-expanding each input type using `etaExpandMMVstr` which is implemented in terms of `etaExpandStrGeneric`. The type generated for these mmvars in this case (with multiple blocks in the context) seems wrong. So later, when the mmvar is abstracted, its entry in Delta is wrong.

The reason that these types is wrong is that the packing substitution generated by `gen_tup_sub` is incorrect. And I traced the problem with that function to the inner function `gen_sub'` which was incorrectly making a recursive call on `pos + 1` when it should have been `pos + k`. Indeed, this bug could only be exposed by trying to flatten a context containing multiple blocks.
