### ISSUE TITLE
Higher-order LF premise variable name conflict with context variable

### ISSUE THREAD

**Issue by MartyO256** [Beluga-lang/Beluga#230]
Load the following signature:
```
LF kind : type = sigma : kind -> (con -> kind) -> kind
and con : type =;
LF cn-of : con -> kind -> type =;
LF kd-wf : kind -> type =
| kd-wf/sigma :
  kd-wf K1 ->
    ({ a : con } cn-of a K1 -> kd-wf (K2 a)) ->
    kd-wf (sigma K1 K2)
;
LF cn-equiv : con -> con -> kind -> type =;
LF kd-equiv : kind -> kind -> type =;

schema conbind-reg =
  some [K : kind, wf : kd-wf K]
  block (a : con, da : cn-of a K);

proof functionality-kd-reg :
  (g : conbind-reg)
  [g, a : con, da : cn-of a (K[..]) |- kd-wf (K'[.., a])] ->
  [g |- cn-equiv C1 C2 K] ->
  [g |- cn-of C1 K] ->
    [g |- kd-equiv (K'[.., C1]) (K'[.., C2])] =
/ total /
?
;
```
Invalid hypotheses are returned after `split x` with the following, which has two variables `a : con`:
```
X3 :
    (g, a : con, da : cn-of a (K[..]), a : con, z2 : cn-of a (X[.., a]) |-
       kd-wf (X1[.., a, a]))
```
The `a : con` from the LF constant `kd-wf/sigma` should have been renamed to avoid this conflict.

A simple workaround for now is to change the conflicting variable name in the statement of the theorem.
```
proof functionality-kd-reg :
  (g : conbind-reg)
  [g, b : con, db : cn-of b (K[..]) |- kd-wf (K'[.., b])] ->
  [g |- cn-equiv C1 C2 K] ->
  [g |- cn-of C1 K] ->
    [g |- kd-equiv (K'[.., C1]) (K'[.., C2])] =
/ total /
?
;
```

**Comment by tsani** [comment]
It looks like contextual name generation (`nameGen.ml`) isn't used for bound variables appearing in the type of a metavariable. If I recall correctly, the types of metavariables generated by splitting are constructed by abstraction, which is known to occasionally generate bogus names... I worked hard to make it not generate overlapping *metavariable* names, but similar work is still needed to generate fresh bound variable names.

**Comment by tsani** [comment]
The fix was easy, since eta-expanded metavariables are all generated by `etaExpandStrGeneric` in `convSigma.ml`. I added a name list parameter to that function, so new bound variables that are introduced are renumbered appropriately.
