### ISSUE TITLE
Non-atomic `cPsi` entry not supported

### ISSUE THREAD

**Issue by MartyO256** [Beluga-lang/Beluga#232]
Non-atomic entries in the `some` clause of schema declarations are currently not supported.

For instance, load the following signature in Harpoon:
```
LF con : type =
| lam : kind -> (con -> con) -> con
and kind : type =
| pi : kind -> (con -> kind) -> kind
;
LF single : kind -> (con -> kind) -> type =;
LF kd-wf : kind -> type =;
LF cn-of : con -> kind -> type =;
LF kind-eq : kind -> kind -> type =;

LF cn-ofp : con -> kind -> type =
| cn-ofp/lam :
  kd-wf K1 ->
  single K1 K1s ->
  ({ a : con } cn-of a K1 -> cn-ofp a (K1s a) -> cn-ofp (C a) (K2 a)) ->
    cn-ofp (lam K1 C) (pi K1 K2)
;

schema conbind-prin =
  some [K : kind, K' : con -> kind]
  block (a : con, d : cn-of a K, dp : cn-ofp a (K' a));

proof cn-ofp-fun :
  (g : conbind-prin)
  [g |- cn-ofp C K] ->
  [g |- cn-ofp C K'] ->
    [g |- kind-eq K K'] =
/ total 1 /
?
;
```
The `conbind-prin` schema contains `K' : con -> kind` in the `some` clause, which would be used in `cn-ofp-fun` when dealing with `cn-ofp/lam` in order to appeal to the induction hypothesis.
For now, in the `cn-ofp-fun` theorem, the tactic `split x` throws an internal error, which reads:
```
Internal error. (State may be undefined.)
Not implemented.
[ctxToSub_mclosed] non-atomic cPsi entry not supported
```
This error is thrown in the `src/core/ctxsub.ml` file:
https://github.com/Beluga-lang/Beluga/blob/ba6c8a8a73680fa315f16d2ff857a19951aa254d/src/core/ctxsub.ml#L104-L106

**Comment by pientka** [comment]
This issue should be fixed now.
