### ISSUE TITLE
Query takes indefinitely long time

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/Beluga#237]
```Beluga
LF nat : type =
  | z : nat
  | s : nat -> nat
;

LF plus : nat -> nat -> nat -> type =
  | p_z : plus z N N
  | p_s : plus N M K -> plus (s N) M (s K)
;

LF tr : type =
  | leaf : tr
  | node : tr -> tr -> tr
;

LF sz : tr -> nat -> type =
  | sz_leaf : sz leaf z
  | sz_node : sz A M -> plus M M L -> sz (node A A) L
;

--query 1 * D : sz (node leaf leaf) S.
```

Beluga does not stop even after emitting 1 solution for the last query.

**Comment by Ailrun** [comment]
By changing the order to `plus M N L -> sz A M -> sz B N -> sz (node A B) (s L)` the query works

**Comment by pientka** [comment]
This is a feature of logic programming ... not a bug.

**Comment by Ailrun** [comment]
@pientka Even when I asked one answer, and it printed one?

**Comment by Ailrun** [comment]
Ah, I was confused about what `1` means in `query 1 *`. The `*` part is the tries, and `1` part is the expected number... I see, this is not a bug.
