### ISSUE TITLE
Invalid coercion of IDs

### ISSUE THREAD

**Issue by MartyO256** [Beluga-lang/Beluga#261]
The types `cid_typ`, `cid_term`, `cid_schema`, etc. in the `./src/core/id.mli` module interface are not abstract. This is necessary in order for the store to (incorrectly) store declarations with respect to the Beluga module in which they are declared.

As a consequence, the OCaml compiler does not complain when a `cid_term` is used in place of a `cid_typ`, for instance. Such ID coercions must be disallowed.

Here are all the occurrences of ID coercion I found:

`Id.cid_comp_typ` used where `Id.cid_comp_const` was expected:

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/coverage.mli#L151-L155

`Id.cid_comp_typ` used where `Id.cid_comp_typdef` was expected:

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/synapx.ml#L132

`Id.cid_comp_typ` used where `Id.cid_comp_cotyp` was expected:

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/store.mli#L184-L185

The logic module performs an incorrect coercion from a computation-level type constant to a computation-level constructor in a duplicated helper.

`Id.cid_comp_typ` used where `Id.cid_comp_const` was expected:

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/logic.ml#L4070-L4072

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/logic.ml#L5246-L5248

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/logic.ml#L5293-L5295

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/logic.ml#L5369-L5371

Harpoon incorrectly uses `Id.cid_comp_const` instead of `Id.cid_prog` for its theorems. That is, Harpoon proofs are treated as computation-level constructors instead of computation-level programs. This mistake likely has to do with a confusion with the naming of `Id.cid_comp_const` which may have been interpreted as computation-level constant instead of constructor.

`Id.cid_comp_const` used where `Id.cid_prog` was expected:

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/harpoon/theorem.mli#L116-L117

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/synint.ml#L720-L723

**Comment by MartyO256** [comment]
@sjjs7 what is the intended behaviour of the `pattern` helper function below? You should assume that `Comp.PatConst (noLoc, cid, mSpineToPSpine mS)` does not type-check because `cid : Id.cid_comp_typ`, but the `Comp.PatConst` constructor expects an `Id.cid_comp_const`.

To me, this looks like we're trying to find a constructor pattern for the given computation-level type. If that's the case, then we should enumerate all possible computation-level constructor patterns for the given type, so `pattern` should return a list of patterns.

https://github.com/Beluga-lang/Beluga/blob/822df29f45342628f272b34c7cb0877cbec0ecdb/src/core/logic.ml#L4066-L4073

**Comment by sjjs7** [comment]
The pattern should be a pattern variable for each case. I will fix this!

**Comment by sjjs7** [comment]
Fixed with commit 5bb2b28. Closing.
