### ISSUE TITLE
Check constructor names for uniqueness

### ISSUE THREAD

**Issue by haselwarter** [Beluga-lang/Beluga#28]
Constructor names should probably be unique at least within one type definition. I don't know how namespaces work in Beluga, but if they work then shadowing across different inductives should probably also be illegal.

This is accepted, and it doesn't seem like a good idea:

```
inductive MyBool : ctype =
  | True : MyBool
  | True : MyBool
;
let true = True ;

rec f : MyBool → Bool =
    fn b =>
    case b of
      | True => ttrue
      | True => ffalse
;

inductive NotBool : ctype =
  | True : NotBool
;
let x : MyBool = true ;
let y = f x ;

```

**Comment by tsani** [comment]
#177 is a more general version of this issue, and invalidates this issue.
