### ISSUE TITLE
[RFC] Capitalise ttrue and ffalse ?

### ISSUE THREAD

**Issue by haselwarter** [Beluga-lang/Beluga#29]
The constructors for ctypes have to start with a capital letter. Shouldn't the constructors for `Bool` be capitalised as well, for consistency?

**Comment by pientka** [comment]
Yes, it would be more consistent -- another, possibly better, option is to simply remove it. We were experimenting with first-class equality and this is the reason why we added booleans, but the treatment of equality is not correct in the presence of dependent types and support for booleans isn't really useful. 

Personally, I would rather remove both first-class equality and booleans. This is related to issue #26 

-Brigitte

**Comment by tsani** [comment]
This is made moot by #105
