### ISSUE TITLE
Error message differs between normal execution and +htmltest flag

### ISSUE THREAD

**Issue by davidthibodeau** [Beluga-lang/Beluga#3]
Commit e3549871742696b91fe7ef75a2dbbfa8585b980c introduces a failing test `t/error/ctx-mismatch2.bel` whose error message described in `t/error/ctx-mismatch2.bel.out` is the following.
>Context mismatch 
>
>expected: [g, x : tm |- tm]
>
>found object in context h, y

However, the output when using the +htmltest is
>Context mismatch 
>
>expected: [g, x : tm |- tm]
>
>found object in context h, x

which causes `./TEST -- +htmltest` and the [Travis-CI build](https://travis-ci.org/Beluga-lang/Beluga/builds/63488356) to fail.

**Comment by ajcave** [comment]
Fixed in commit ae81edeab
