### ISSUE TITLE
Internal error (indexed inductives)

### ISSUE THREAD

**Issue by haselwarter** [Beluga-lang/Beluga#30]
```
inductive Flip : Bool → Bool → ctype =
  | Flip0 : Flip ffalse ttrue
  | Flip1 : Flip ttrue ffalse
;
```
yields
```
File "~/su/opsem/indexed/minimal_index.bel", line 1, characters 31-36:
Internal error (please report as a bug):
Can't unmix. At File "~/su/opsem/indexed/minimal_index.bel", line 1, characters 24-28
```
As far as I can tell from the userguide, my error is that I try to use index with a ctype while only LF types can serve as index.

**Comment by tsani** [comment]
The notion of "mixtyp" was removed completely in the parser overhaul, and the Bool type was also removed in a separate patch.
