### ISSUE TITLE
Identitiy substitutions in blocks (new syntax)

### ISSUE THREAD

**Issue by pientka** [Beluga-lang/Beluga#7]
This is an issue with the new syntax where we omit writing identity substitutions. 

For example, the following works:
 
tm: type.
tp: type. 
oft: tm -> tp -> type.
schema xtG = some [t:tp] block (x:tm, u:oft x t);

inductive Rxrt: {h:xtG} prop =
| Rxrt_nil : Rxrt []
| Rxrt_cons: Rxrt  [h] ->
     Rxrt [h, b:block(x:tm, v:oft x A[..])];

In this case it solves the unification problem: A[ ^1] =?= ?Y[ ^1 ] during schema checking

However, writing 

inductive Rxrt: {h:xtG} prop =
| Rxrt_nil : Rxrt []
| Rxrt_cons: Rxrt  [h] ->
     Rxrt [h, b:block(x:tm, v:oft x A)];

does not work, since it tries to solve the unification problem: A[ ^0 ] =?= ?Y[ ^1 ].

**Comment by ajcave** [comment]
What do you expect to happen if you write the following?

```
inductive Rxrt: {h:xtG} prop =
| Rxrt_nil : Rxrt []
| Rxrt_cons: Rxrt [h] -> Rxrt [h, b:block(x:tm, v:oft x A[..,x])];
```

**Comment by pientka** [comment]
this is ill-typed, given the schema, in my opinion; the fact that t:tp is quantified outside it indicates it *only* depends on assumptions built up in the context. If you want the second element of the block to depend on the first, one would need the following schema:

rel: tp -> tp -> type.
schema xtG = some [t:tp -> tp] block (x:tp, u: rel x (T x)

**Comment by ajcave** [comment]
Then I'm not sure in what sense this is an issue. It's perhaps confusing when you first encounter it, and perhaps we can improve the error message. But I don't think it's a bug.

**Comment by pientka** [comment]
Are you saying that 

inductive Rxrt: {h:xtG} prop =
| Rxrt_nil : Rxrt []
| Rxrt_cons: Rxrt [h] ->
Rxrt [h, b:block(x:tm, v:oft x A)];

is equivalent to 

inductive Rxrt: {h:xtG} prop =
| Rxrt_nil : Rxrt []
| Rxrt_cons: Rxrt [h] ->
Rxrt [h, b:block(x:tm, v:oft x A[.., x])];

and not 

inductive Rxrt: {h:xtG} prop =
| Rxrt_nil : Rxrt []
| Rxrt_cons: Rxrt [h] ->
Rxrt [h, b:block(x:tm, v:oft x A[..])];

?

If this is the case, then I agree  that this is not a bug, but we should not give 

Type block (x:tm, v:oft x (A ..)) doesn't check against schema .

as an error, but 

 Type block (x:tm, v:oft x A[ .., x]) doesn't check against schema .

**Comment by ajcave** [comment]
Yes. The error message is bogus; the pretty printer seems to just print any Shift 0 as "..", which is wrong. The error message should say 

```
Type block (x:tm, v:oft x A[.., x]) doesn't check against schema .
```
