### ISSUE TITLE
Internal error: Expected substitution variable

### ISSUE THREAD

**Issue by nad** [Beluga-lang/Beluga#75]
The following code triggers an internal error in Beluga f65d501160913a10f4b749c620711f0678c58c06:
```
LF unit : type =
| unit : unit
;

rec f : {#x : [⊢ unit]} [⊢ unit] =
mlam X ⇒ impossible [⊢ #X]
;
```
Error message:
```
Internal error (please report as a bug):
Expected substitution variable
```
(The code is accepted if `X` is replaced with `x` in the penultimate line.)

**Comment by tsani** [comment]
The overhaul of the parser and preliminary scope checking in index.ml make this situation give an appropriate error, that `#X` is not in scope.
