### ISSUE TITLE
Internal error in reconstruct.ml

### ISSUE THREAD

**Issue by nad** [Beluga-lang/Beluga#78]
The following code triggers an internal error in Beluga f65d501160913a10f4b749c620711f0678c58c06:
```
LF empty : type =
;

LF t : type =
| c : (t → t) → t
;

schema ctx = t;

rec foo : {γ : ctx} [γ ⊢ t] → [⊢ empty] =
mlam γ ⇒ fn x ⇒ case x of
| [γ ⊢ c (\x. X)] ⇒
  foo [_] [γ, x ⊢ X[..]]
;
```
Error message:
```
Uncaught exception.
Please report this as a bug.

## Type Reconstruction: [...]/bug.bel ##
File "src/core/reconstruct.ml", line 184, characters 52-57: Pattern matching failed
```

**Comment by tsani** [comment]
The error message for this is now appropriate, and says that a type annotation is needed for the bound variable `x` on the second to last line. The need for these type annotations is annoying, and could be removed in some simple cases (as in this example). See #182 and #183 for more details.
