### ISSUE TITLE
Pretty printing of substitutions isn't updated to new syntax

### ISSUE THREAD

**Issue by ajcave** [Beluga-lang/Beluga#9]
Pretty printing still prints things like `oft (M .. x) T` (old syntax) when it should print something like `oft M[..,x] T[]` (new syntax)

**Comment by MartyO256** [comment]
This was fixed in https://github.com/Beluga-lang/Beluga/commit/bf97ef2074f60f51122d15ecd7df7716705b1eb1 https://github.com/Beluga-lang/Beluga/commit/55fd9bbe78765fb42bc921a2a830f1a329f2a917.
